title:   Noah Thiemke
description: |
  <strong>Phone</strong>: (910) 751-9221<br>
  <strong>Email</strong>: nthiemke@ad.unc.edu<br>
  <strong>LinkedIn</strong>: <a href="https://linkedin.com/in/noahthiemke">View Profile</a>
logo: /assets/images/NDTSmaller.png
show_downloads: false
theme: jekyll-theme-minimal
css:
  - /assets/css/custom.css
