title:   Noah Thiemke
description: |
  **Phone**: (910) 751-9221  
  **Email**: nthiemke@ad.unc.edu  
  **LinkedIn**: [Link](https://www.linkedin.com/in/noahthiemke/)

logo: /assets/images/NDTSmaller.png
show_downloads: false
theme: jekyll-theme-minimal
